// <auto-generated />
using System;
using EFClient.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFClient.Repo.Migrations
{
    [DbContext(typeof(ZupContext))]
    partial class ZupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFClient.Dominio.Cliente", b =>
                {
                    b.Property<int>("NumeroChapaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NomeLiderNumeroChapaId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumeroChapaId");

                    b.HasIndex("NomeLiderNumeroChapaId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("EFClient.Dominio.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteNumeroChapaId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteNumeroChapaId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("EFClient.Dominio.Cliente", b =>
                {
                    b.HasOne("EFClient.Dominio.Cliente", "NomeLider")
                        .WithMany()
                        .HasForeignKey("NomeLiderNumeroChapaId");
                });

            modelBuilder.Entity("EFClient.Dominio.Telefone", b =>
                {
                    b.HasOne("EFClient.Dominio.Cliente", null)
                        .WithMany("Telefone")
                        .HasForeignKey("ClienteNumeroChapaId");
                });
#pragma warning restore 612, 618
        }
    }
}
